name: aws_monitoring
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^0.1.1
  fluttertoast: ^3.1.3
  shared_preferences: ^0.5.6
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  dio: ^3.0.8
  states_rebuilder: ^1.14.3
  curved_navigation_bar: ^0.3.3
  cupertino_icons: ^0.1.2
  pull_to_refresh: ^1.5.7
  firebase_core: ^0.4.4
  firebase_auth: ^0.15.1
  cloud_firestore: ^0.13.2+1  
  firebase_storage: ^3.1.1
  path_provider: ^1.4.4
  flutter_launcher_icons: ^0.7.4
  provider: ^3.2.0
  uuid: ^2.0.4
  flutter_datetime_picker: ^1.3.8
  basic_utils: ^1.5.0

flutter_icons:
    image_path: assets/logo_bmkg.png
    android: launcher_icon
    ios: true
dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.2.2
  build_runner: ^1.7.3
  hive_generator: ^0.7.0+2
  configurable_expansion_tile: ^1.0.0

flutter:
  uses-material-design: true
  assets:
        - assets/logo_bmkg.png
